Shortened the negative intermessage gap to cope with the new messages. Added a second menu name for the embedded version of X-RAAS. Added aircraft-type specific build option switches.

diff --git a/build_release b/build_release
--- a/build_release
+++ b/build_release
@@ -154,8 +154,9 @@ function install_xtra_files() {
 embed=''
 embed_suffix=''
 nodoc=no
+acf_type=''
 
-while getopts "edh" opt; do
+while getopts "edht:" opt; do
 	case "$opt" in
 	e)
 		embed="-e"
@@ -164,9 +165,20 @@ while getopts "edh" opt; do
 	d)
 		nodoc=yes
 		;;
+	t)
+		case "$OPTARG" in
+			*)
+				echo "Invalid aircraft type." \
+				    "Try \"$0 -h\" for help" >&2
+				exit 1
+				;;
+		esac
+		embed="-e"
+		embed_suffix="_embed"
+		;;
 	h)
 		cat << EOF
-Usage: $0 [-eh]
+Usage: $0 [-eh] [-t <acf_type>]
 Options:
   -d : Continue even if the documentation build failed. Useful if you don't
        have pdfTeX installed and just want to test build.
@@ -174,6 +186,8 @@ Options:
        when a globally installed version of X-RAAS is detected to prevent
        duplicated annunciations. Embeddable versions also relocate their config
        files and data cache so that they don't interfere with a global version.
+  -t <acf_type>: Build an embeddable version specifically geared towards a
+       particular aircraft model. This implies "-e".
   -h : Show this help screen.
 EOF
 		exit
@@ -207,14 +221,14 @@ rm -rf X-RAAS2${embed_suffix}
 
 case `uname` in
 Linux)
-	( cd qmake && ./build-win-lin $embed ) && \
+	( cd qmake && ./build-win-lin $embed -t "$acf_type" ) && \
 	    mkdir -p X-RAAS2${embed_suffix}/{32,64} && \
 	    cp qmake/output/32/{win,lin}.xpl X-RAAS2${embed_suffix}/32 && \
 	    cp qmake/output/64/{win,lin}.xpl X-RAAS2${embed_suffix}/64 && \
 	    install_xtra_files
 	;;
 Darwin)
-	( cd qmake && ./build-mac $embed ) && \
+	( cd qmake && ./build-mac $embed -t "$acf_type" ) && \
 	    mkdir -p X-RAAS2${embed_suffix}/{32,64} && \
 	    cp qmake/output/32/mac.xpl X-RAAS2${embed_suffix}/32 && \
 	    cp qmake/output/64/mac.xpl X-RAAS2${embed_suffix}/64 && \
