Rewritten documentation in pdfTeX to obtain more consistent formatting.

diff --git a/build_release b/build_release
--- a/build_release
+++ b/build_release
@@ -54,8 +54,9 @@ DIST_FILES=(
     'api/c/XRAAS_ND_msg_decode.h'		'Documentation/api/c'
     'api/c/XRAAS_ND_msg_decode.c'		'Documentation/api/c'
     'api/c/test_sample.c'			'Documentation/api/c'
-    'Documentation/Avionics Integration Guide.pdf'		''
-    'Documentation/User Manual.pdf'				''
+    'Documentation/AvionicsIntegrationGuide/AvionicsIntegrationGuide.pdf'
+	'Documentation'
+    'Documentation/UserManual/UserManual.pdf'	'Documentation'
     'data/fonts/Aileron/Aileron-Regular.otf'			''
     'data/fonts/ShareTechMono/OFL.txt'				''
     'data/fonts/ShareTechMono/ShareTechMono-Regular.ttf'	''
@@ -177,6 +178,12 @@ fi
 
 if ! ( cd FreeType && ./build_freetype_deps ); then
 	echo "FreeType build failed" >&2
+	exit 1
+fi
+
+if ! ( cd Documentation && make ); then
+	echo "Documentation build failed, please make sure" \
+	    "you have pdfTeX installed." >&2
 	exit 1
 fi
 
